### ISSUE TITLE
The code is missing the necessary yaml file

### ISSUE THREAD

**Issue by jmwang0117** [real-stanford/im2Flow2Act#1]
![image](https://github.com/user-attachments/assets/9f5d29c4-c0cf-4262-9c5c-a20547ba114d)

**Thanks for your excellent work. When I evaluated, I found that there was no yaml file related to data/get_bbox.yaml in the config directory. Can you add this file?**

**Comment by mengdaxu** [comment]
Thanks for pointing out. It's been updated now.
