### ISSUE TITLE
config/data/get_bbox.yaml file is missing

### ISSUE THREAD

**Issue by GuaguaguaLiu** [real-stanford/im2Flow2Act#2]
Hello,

Thank you for your excellent work! I noticed that the `config/data/get_bbox.yaml` file is missing. Could you please add this file ?

Thanks!

**Comment by ZorAttC** [comment]
How did you fix that?I need  your help sincerely.

**Comment by mengdaxu** [comment]
Sorry, forgot to commit the data configuration. It's been updated now.

**Comment by ZorAttC** [comment]
> Sorry, forgot to commit the data configuration. It's been updated now.

Thank you so much for the quick reply : )
