### ISSUE TITLE
Regarding the difference in evaluation code

### ISSUE THREAD

**Issue by jmwang0117** [real-stanford/im2Flow2Act#3]
Thanks for your excellent work! 

Is there any difference between **evalute_flow_diffusion_policy.py** and **evaluate_from_flow_generation.py** ?

**Comment by mengdaxu** [comment]
**evalute_flow_diffusion_policy.py** evaluate the flow diffusion policy with ground truth flow while **evaluate_from_flow_generation.py** evaluate the policy with generated flow.
