### ISSUE TITLE
What should be included in the raw data from the real world and simulations before further data preprocessing?

### ISSUE THREAD

**Issue by GuaguaguaLiu** [real-stanford/im2Flow2Act#4]
Hello,

Thank you for your excellent work. 

When looking at **Real-World data preprocessing** (in `scripts/data_script/realworld_data.md`) and **Simulation data preprocessing** (in `simulation_data.md`), I have a question about what the raw data from real world and simulations should include.  For example, what form should the data_buffer (in `scripts/data_script/convert_simulation_dataset.py`) take?

Thanks!

**Comment by mengdaxu** [comment]
Hi, 

Thanks for your kind words. All data are stored under zarr format.
