### ISSUE TITLE
The recommended GPU configuration to train the flow generation

### ISSUE THREAD

**Issue by ZorAttC** [real-stanford/im2Flow2Act#6]
Dear Author,
Thank you for your amazing work and generou open source behaviour.
And I want to train my own flow generation model using the real world dataset.How many demonstrations for  each task do you think that will make the training  to converge? And as a greenhand to DL, I wanna know how much GPU RAM is needed to train the model,any specific info? Again Thank you so much.

**Comment by mengdaxu** [comment]
Hi, 

Thanks for your kind words. We train our model on 4 L40s for roughly 1 or 2 days. 

In terms of number of demonstrations, it really depends on your specific tasks. I would say roughly 100 to 200 demonstrations is a good starting point.

**Comment by ZorAttC** [comment]
Thank you for the supportive response.
