### ISSUE TITLE
Image size issue when training the flow generation model

### ISSUE THREAD

**Issue by jmwang0117** [real-stanford/im2Flow2Act#7]
Thanks for your great work! 

I noticed that the image size you input to Animatediff is **224 x 224**, is this required? Does the _"openai/clip-vit-large-patch14"_ model only accept images of this size? I tried to input **480 x 640** images but encountered dimension issues even when I changed the size in the yaml file to [480,640].

Looking forward to your reply!

**Comment by mengdaxu** [comment]
Sorry for the late reply. Yes, it is desired input size for clip model. You may manually resize your image to 224x224 before passing to the model.
