### ISSUE TITLE
Simulated data generation code

### ISSUE THREAD

**Issue by MalcomF1** [real-stanford/im2Flow2Act#9]
Hi, what an awesome work! I wonder whether you have published the simulated data generation code, described in _C.1 Simulated Exploration Data_ of your paper. Thanks!

**Comment by Wangmmstar** [comment]
> Hi, what an awesome work! I wonder whether you have published the simulated data generation code, described in _C.1 Simulated Exploration Data_ of your paper. Thanks!

Hi Malcom,

Have you found the simulated data generation code? I only found the simulation environment code for evaluation but no generation code. Thank you

Best,
June
